name: Build and test

on:
  push:
    branches: [main]
  pull_request: {}
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      CMAKE_GENERATOR: Ninja

    steps:
      - uses: actions/checkout@v7
      - run: cmake -Bbuild -S.
      - run: cmake --build build
      - run: bash ./tests/run.sh
